import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Jersey_25 } from 'next/font/google';

const jersey_25 = Jersey_25({
  weight:"400",
  subsets: ['latin'], // Ensure 'latin' subset is specified
  display: 'swap',
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jersey_25.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
